<script>
import {IUXTray, IUXTrayHolder} from 'svelte-iux';
import {IUXRevealArea, IUXRevealContainer} from 'svelte-iux';

import Notifications from 'svelte-notifications';
import {notifications} from './notifications.js';
  
import SourceUI from './interfaces/SourceUI.svelte';
import ViewModelUI from './viewmodels/ViewModelUI.svelte';

import {resultDataStore} from './stores.js';

// Initial visual states
// TODO automatically preserve some application state (in localstorage?)
// TODO provide for reset of defaults (e.g. delete stored state)
let tray1Intro = false;
$: tray1IntroButtonText = tray1Intro ? '<<Less' : 'More>>';
let tray1DataSource = true;
</script>

<style>
	h1 {
		color: purple;
	}
</style>

<Notifications>
  <h1>Visualisation Lab</h1>

  <IUXTrayHolder>
      <p>
        VisLab is an experimental workspace for visual analysis of data
        returned from searches on a wide variety of data sources.
        <span on:click={() => tray1Intro = !tray1Intro}>{tray1IntroButtonText}</span>
      </p>
      <IUXRevealArea reveal={tray1Intro}>
        <p>
          It supports
          multiple mappings from results to different 'view models' and multiple
          presentations (graph, chart, table etc) depenind on the view models
          generated by the class which implements querying of a data source, and the
          queries it implements. VisLab has been designed to be easily extendable, for
          example adding a new kind of data source involves creating one simple
          JavaScript class. VisLab is open source, code on 
          <a href='https://github.com/theWebalyst/visualisation-lab'>github</a>.
        </p>
        <p>
          Powered by Sveltejs, Vega-Lite and D3js, and using an experimental 
          <a href='https://github.com/theWebalyst/visualisation-lab/svelte-iux'>svelte-iux</a>
          components to provide a didactic, incremental user experience (iUX).
        </p>
      </IUXRevealArea>

    <IUXTray >
    hello
      <div style='height: auto;'>
        <SourceUI/>
      </div>
      <IUXRevealArea>
        Area 1.2
      </IUXRevealArea>

      <IUXRevealArea>
        Area 1.3
      </IUXRevealArea>
    </IUXTray>

    <IUXTray>
      Tray 2
      <IUXRevealArea>
        Area 2.1
      </IUXRevealArea>
      <IUXRevealArea>
        Area 2.2
      </IUXRevealArea>
      <IUXRevealArea>
        Area 2.3
      </IUXRevealArea>
    </IUXTray>
  </IUXTrayHolder>

  <ViewModelUI resultDataStore={resultDataStore}/>
</Notifications>
